--PROYECTO INTEGRADOR--

--CREAMOS SCHEMAS--

CREATE SCHEMA VENTAS;
GO

CREATE SCHEMA LOGISTICA;
GO

CREATE SCHEMA ANALYTICS;
GO

-- CREACION DE TABLAS POR SCHEMA--

-- ESQUEMA DE VENTAS ----------------------------------

CREATE TABLE VENTAS.CLIENTES (
ID_CLIENTE INT PRIMARY KEY,
NOMBRE VARCHAR(100) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
FECHA_REGISTRO DATE NOT NULL,
);
GO

-- ESQUEMA DE LOGISTICA ------------------------------

CREATE TABLE LOGISTICA.ENVIOS (
ID_ENVIOS  INT PRIMARY KEY,
ID_CLIENTE INT,
DESTINO VARCHAR(255) NOT NULL,
FECHA_ENVIO DATE NOT NULL,
ESTADO VARCHAR(50) DEFAULT 'Pendiente',
);
GO

-- ESQUEMA DE ANALYTICS -------------------------------

CREATE TABLE ANALYTICS.REPORTES(
ID_REPORTE INT PRIMARY KEY NOT NULL,
TITULO VARCHAR(150) NOT NULL,
DESCRIPCION VARCHAR(500),
FECHA_CREACION DATE NOT NULL,
);
GO

-- CREACION DE ROLES Y PERMISOS ----------------------

CREATE ROLE ADMIN_DB;
GO

CREATE ROLE ANALISTA_DATOS;
GO 

CREATE ROLE OPERADOR_LOGISTICA;
GO 

-- PERMISOS ADMIN --

GRANT CONTROL ON SCHEMA::VENTAS TO ADMIN_DB;
GRANT CONTROL ON SCHEMA::LOGISTICA TO ADMIN_DB;
GRANT CONTROL ON SCHEMA::ANALYTICS TO ADMIN_DB;
GO 

-- PERMISOS ANALISTA --

GRANT SELECT ON SCHEMA::VENTAS TO ANALISTA_DATOS;
GRANT SELECT ON SCHEMA::ANALYTICS TO ANALISTA_DATOS;
GO

-- PERMISOS PARA OPERADOR --

GRANT SELECT, INSERT, UPDATE ON SCHEMA::LOGISTICA TO OPERADOR_LOGISTICA;
GO
